In [1]:
from sklearn.datasets import make_regression

In [4]:
!pip install plotly

DEPRECATION: celery 5.1.2 has a non-standard dependency specifier pytz>dev. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of celery or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063


In [2]:
import plotly.express as px

In [3]:
import pandas as pd

In [4]:
import numpy as np

In [5]:
x,y=make_regression(n_samples=100,n_features=2,n_informative=2,n_targets=1)

In [6]:
x

array([[ 0.00474228, -1.17627484],
       [-0.83565829, -1.06135709],
       [-0.84060119, -0.68705325],
       [ 0.9586695 ,  0.41639263],
       [-2.01880085,  0.83387502],
       [-2.62189168,  0.74268491],
       [-1.59668172,  0.32204445],
       [ 1.56485103, -1.73510258],
       [ 0.24292736, -1.38724919],
       [-0.30584107,  1.50380406],
       [-0.08502552, -0.56014237],
       [-1.33901568, -1.13004834],
       [ 1.01894397,  1.43485736],
       [-1.57553513, -0.58004627],
       [-0.85162834, -1.43032342],
       [-1.51743365,  1.27024917],
       [ 0.15591098, -0.14572696],
       [ 1.4403215 , -0.03624121],
       [ 0.59495105, -0.0456623 ],
       [ 1.7532106 ,  0.6316588 ],
       [-0.34901886,  0.09286814],
       [ 0.32298601, -1.00146203],
       [-1.10714788,  1.407745  ],
       [-0.15771813, -0.91013893],
       [ 1.50775167, -0.07099229],
       [-0.38189488, -1.6825632 ],
       [-0.05482022,  0.26429205],
       [-0.60004524, -0.38097979],
       [-0.0589846 ,

In [7]:
y

array([ -48.6072972 ,  -78.82511392,  -63.50067876,   57.18590342,
        -49.44440247,  -78.33462306,  -53.10790996,   -6.84627496,
        -47.44517589,   49.66204751,  -26.7804296 , -102.62993551,
        101.95216092,  -89.65614625,  -94.7986973 ,  -10.46693333,
          0.44422638,   58.45687471,   22.87323004,   99.1942239 ,
        -10.6764642 ,  -28.10567419,   12.31808293,  -44.32829906,
         59.82213724,  -85.70936174,    8.68355395,  -40.78707114,
        -19.00515003,  -75.47981618,   14.29641066,   22.60547003,
         55.73024843,   44.37743881,    9.09691568,  -25.23077693,
         56.3191751 ,    0.70500423,  -73.95567843,   22.76559155,
          1.41818027,  -16.67555524,   49.75455862,   35.95755201,
         43.02649449,   -9.9159273 ,   13.06342956,   41.58309911,
         -7.28195308,   30.72898621,   13.89367148,   43.69422384,
        -10.49408642,  -42.79838279,   65.91756178,  -97.78743374,
         -3.2715299 ,   66.38990703,    3.28296751,   14.02074

In [8]:
data=pd.DataFrame({
    "feature1":x[:,0],
    "feature2":x[:,1],
    "target": y
})

In [9]:
data

feature1  feature2     target
0   0.004742 -1.176275 -48.607297
1  -0.835658 -1.061357 -78.825114
2  -0.840601 -0.687053 -63.500679
3   0.958670  0.416393  57.185903
4  -2.018801  0.833875 -49.444402
..       ...       ...        ...
95 -0.045114 -1.085357 -46.910564
96  0.118102  0.467032  24.294167
97 -1.195862  1.616269  17.276767
98  0.802122 -0.190704  25.479814
99  0.822534  0.171207  41.345608

[100 rows x 3 columns]

In [10]:
data.head(3)

feature1  feature2     target
0  0.004742 -1.176275 -48.607297
1 -0.835658 -1.061357 -78.825114
2 -0.840601 -0.687053 -63.500679

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [29]:
x_train

array([[-0.60129327,  1.70512464],
       [-1.74275743,  0.03069051],
       [ 0.12059143,  0.74564115],
       [-1.19586236,  1.61626935],
       [-0.18765369,  0.26740762],
       [-2.01880085,  0.83387502],
       [-0.67432163,  0.27467317],
       [-0.60004524, -0.38097979],
       [-0.94498431,  0.86930232],
       [-0.25344239,  0.07878468],
       [ 0.04953417,  0.16828224],
       [-1.47597817,  1.62371686],
       [-1.37645086, -1.32949812],
       [ 2.43133839, -0.85076475],
       [-0.20973073,  0.95105333],
       [-2.29515996,  1.59882729],
       [-1.22567583, -0.46091652],
       [-0.27396758,  1.57851196],
       [-0.20671304, -0.04551904],
       [-0.46875446,  0.41103903],
       [-0.0589846 , -0.3988734 ],
       [ 0.82253371,  0.17120727],
       [ 0.66743774,  0.71123972],
       [-0.84060119, -0.68705325],
       [-1.15475064,  1.17561281],
       [ 0.24292736, -1.38724919],
       [-1.13984357,  0.99940848],
       [-2.62189168,  0.74268491],
       [-0.83565829,

In [30]:
from sklearn.linear_model import LinearRegression

In [31]:
obj=LinearRegression()

In [32]:
obj.fit(x_train,y_train)

LinearRegression()

In [33]:
m=obj.coef_

In [34]:
m

array([41.62998026, 41.49091428])

In [35]:
b=obj.intercept_

In [36]:
b

1.7763568394002505e-15

In [37]:
x_test

array([[-1.10714788,  1.407745  ],
       [-0.05479794,  1.92096784],
       [ 0.5900554 , -0.41801186],
       [ 1.7532106 ,  0.6316588 ],
       [-0.43432782, -0.5957286 ],
       [ 0.15591098, -0.14572696],
       [-0.31436942,  0.86025251],
       [ 0.34433166, -0.00756252],
       [ 1.01894397,  1.43485736],
       [-0.15771813, -0.91013893],
       [-0.03550946, -0.20336185],
       [ 0.55858063,  1.03965427],
       [ 0.00474228, -1.17627484],
       [-1.51743365,  1.27024917],
       [ 1.42280054,  0.60435518],
       [ 0.14069411, -0.85464562],
       [ 1.49267868,  0.17480582],
       [ 0.47626974,  0.4296907 ],
       [ 1.50775167, -0.07099229],
       [ 0.38558397, -0.04230908]])

In [38]:
y_test

array([ 12.31808293,  77.42147453,   7.22030022,  99.1942239 ,
       -42.79838279,   0.44422638,  22.60547003,  14.02074433,
       101.95216092, -44.32829906,  -9.9159273 ,  66.38990703,
       -48.6072972 , -10.46693333,  84.30640722, -29.60293541,
        69.39303702,  37.65536012,  59.82213724,  14.29641066])

In [39]:
y=b+(59.80285499*-0.50521247)+(59.13749864*-0.53380014)

In [40]:
y

-61.78075313583153

In [41]:
graph=px.scatter_3d(data,x="feature1",y="feature2",z="target")

In [42]:
graph.show()

In [43]:
import plotly.graph_objects as go


import numpy as np

x = np.linspace(-5, 5, 10)
y = np.linspace(-5, 5, 10)

xGrid, yGrid = np.meshgrid(y, x)
final = np.vstack((xGrid.ravel().reshape(1,100),yGrid.ravel().reshape(1,100))).T

z_final = obj.predict(final).reshape(10,10)

z = z_final

graph = px.scatter_3d(data, x='feature1', y='feature2', z='target')

graph.add_trace(go.Surface(x = x, y = y, z =z ))

graph.show()