# Importing data

In [1]:
!pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/28/75/3b679b41713bb60e2e8f6e2f87be72c971c9e718b1c17b8f8749240ddca8/numpy-1.26.2-cp312-cp312-win_amd64.whl.metadata
     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     ---------------------------------------- 61.2/61.2 kB 1.6 MB/s eta 0:00:00
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
    --------------------------------------- 0.3/15.5 MB 5.7 MB/s eta 0:00:03
   - -------------------------------------- 0.7/15.5 MB 7.3 MB/s eta 0:00:03
   -- ------------------------------------- 1.2/15.5 MB 8.1 MB/s eta 0:00:02
   ---- ----------------------------------- 1.6/15.5 MB 8.3 MB/s eta 0:00:02
   ---- ----------------------------------- 1.9/15.5 MB 8.0 MB/s eta 0:00:02
   ---- ----------------------------------- 1.9/15.5 MB 8.2 MB/s eta 0:00:02
   ---- ----------------------------------- 1.9/15.5 MB 8.2 MB/s eta 0:00:02
   ---- --------------------------


[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: C:\Users\Dell\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

# ndarray:

In [43]:
# object created by array method in numpy is called ndarray
# array

In [6]:
arr=np.array(12)
type (arr)

<class 'list'>


In [5]:
arr=np.array(2)
type(arr)

numpy.ndarray

# ndim show the dimension

In [13]:
x=np.array([[[1,3,4,3],[1,2,3,4]],[[2,3,4,5],[3,4,5,5]]])
x.ndim
x

array([[[1, 3, 4, 3],
        [1, 2, 3, 4]],

       [[2, 3, 4, 5],
        [3, 4, 5, 5]]])

In [7]:
a=np.array([[1,2],[2,3]])
a
a.ndim

2

# indexing

In [19]:
arr=np.array([[1,2,3,4],[2,3,4,0]])
arr[1][1]

3

In [15]:
arr[1]

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

# slicing

In [25]:
# [start:end:increment]
# [0:n-1:1]

In [ ]:
# sort
arr=([1,22,4,23,5])
arr.sort()

arr[::-1]

In [57]:
# where
arr=np.array([[1,22,4,23,5],[1,3,4,5,5]])
np.where(arr==1)

(array([0, 1], dtype=int64), array([0, 0], dtype=int64))

In [22]:
arr=([[1,2,42,23,55],[32,4,3,6,7]],[[1,2,3,4,5],[1,23,4,4,3]])
arr[1][0]

[1, 2, 3, 4, 5]

In [20]:
arr[1]

array([2, 3, 4, 0])

# shape : for rows and columns

In [2]:
import numpy as np
arr=np.array([[1,2,3],[2,3,4]])
arr.ndim
arr.shape

(2, 3)

# reshape : changing the rows and columns

In [3]:
arr=np.array([1,2,3,4,4,3,2,1,3,10])
arr.reshape(2,5)
# arr.shape


array([[ 1,  2,  3,  4,  4],
       [ 3,  2,  1,  3, 10]])

In [5]:
#  -1 
import numpy as np
arr=np.array([2,34,3,2,4,2,3,4,3])
arr.reshape(3,-1)
arr.reshape(-1,3)

array([[ 2, 34,  3],
       [ 2,  4,  2],
       [ 3,  4,  3]])

In [35]:
import numpy as np
arr=np.array([[ 1,  2,  3,  4,  4],
       [ 3,  2,  1,  3, 10]])
arr.reshape(-1)

array([ 1,  2,  3,  4,  4,  3,  2,  1,  3, 10])

In [50]:
a=np.array([1,2,3])
b=np.array([1,2,3])
a+b

array([2, 4, 6])

In [39]:
# concatenate
a=np.array([1,2,3])
b=np.array([1,2,3])
zx=np.concatenate([a,b])
zx

array([1, 2, 3, 1, 2, 3])

In [31]:
# split
a=np.array([[2,3,5],[2,3,4]])
np.split(a,1)
a


array([[2, 3, 5],
       [2, 3, 4]])

In [7]:
# stack
a=np.array([1,2,3])
b=np.array([1,2,3])
x=np.stack((a,b),axis=0)
x

array([[1, 2, 3],
       [1, 2, 3]])